### ISSUE TITLE
Feature Request: Display Enhancements

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [janlelis/uke#1]
Hi there,

Thank you for this wonderful gem (that turned out to be a pun). This will be such a cool thing to teach some of my students (Linux and Ukulele? Awesome Mix!)

I think it'd be nice if finger numbers could also be displayed; and also fret numbers, as required. It'd be nice, too, if we could increase the chord library.

I am currently watching this repo, and, should I ever get around to learning ruby, I would also like to make some PRs to this neat gem in the future.

Please keep up the good work. :+1:

**Comment by janlelis** [comment]
Thanks for the praise and suggestions.

I've just released 1.0.1 which supports finger numbers!

**Comment by peanutbutterandcrackers** [comment]
@janlelis - You are most welcome. :) Thank you for the prompt work but I am afraid some bugs and some work still remain unfinished... I have put some comments in the discussion of the now closed PR.
